### ISSUE TITLE
[KPT]#1 프로젝트 방향성 및 주제 논의

### ISSUE THREAD

**Issue by kim-kyoungyeon** [kim-kyoungyeon/aws_first_project#1]
- date : 2023/01/11
- subject : 팀 프로젝트 주제 논의 
- contents
     - dev 1 : 챗봇, 자동 메시지 전달 서비스 aws 이용
     - dev 2 : 쇼핑몰 웹 애플리케이션 배포 
     - dev 3 : azure과 aws 를 이용한 onpromise 서버 연결 및 가상 서버 배포

# KEEP 유지 항목
- 아직 미정
# Problem  문제라고 생각하는 항목
- null 
# Todo List 앞으로 해야할 일 목록 
- [x] 빠른 시일내에 주제 정하고 바로 실행할 것. 
- [x] 모르는 기술 함께 공부하기 ex) aws , azure
- [ ] git 사용 규칙 정하기
- [x] devlog git issue에 쓰시는 것 추천. 
- [ ] commit lints 정하기
- [ ] issue 및 PR 규칙 정하기
