### ISSUE TITLE
 [Meet#0]20230125 여영돈 외 2명 

### ISSUE THREAD

**Issue by kim-kyoungyeon** [kim-kyoungyeon/aws_first_project#5]
- TeamMem : 여영돈,이원조,김경연
- Duration : 4weeks
- Time: 12:30 pm ~ 1:40 pm

# Contents
- 프로젝트 주제에 대해 의견이 갈린다 
  - 5 AWS에서 Lambda 기반의 하이브리드 클라우드 환경 웹서비스하기
  - 6 AWS 통한 멀티 리전환경과 하이브리드 클라우드 환경 웹서비스하기   🎉 **[확정]**
  - 7 AWS EKS 기반 물류 관리 자동화 구축
  - 8 IaC 기반 Beanstalk을 이용한 티켓팅 사이트 자동화 배포

총 4개인데 솔직히 도전한다면 물류 관리에 도전하고 싶다(개인적으로)
하지만 백엔드 경력자분께서 무난한 걸 원하시고, 또 세명다 인프라로는 전공자도 아니다보니,
무난하게 5,6 번중에서 수렴되지않을까 하는게 내 생각

- 여영돈님께서 계속계속 계속 자료를 주신다. aws 자격증따라구... 그저 감사할 뿐
- 두분다 예전 서브넷 물어봤을 때나 , 확실히 네트워크쪽이  박식하신것 같다. 
- 어떤 프로젝트든, 추가 기능으로 쿠버네티스를 활용하면 좋겠다는 의견이 나옴.
- 도커만 성공해도 쿠버네티스는 시간을 좀 더 들이면 되지않을까 라고 생각함.
- 

# Question
- 멀티리젼 설정?
- 프로젝트 멘토링이 뭔데?
- 마이그레이션이 뭐죠?
- 도커로 다른 언어끼리 소통이 가능함. 어떻게 하냐...? 자료 찾는게 부족했다. 좀 더 찾아보자

# Todo List
- [x]  도커 관련 자료 찾고 만들어보기
- [ ]  aws 무료 인강 완료하기
- [ ]  프로젝트에 필요한 필수적인 aws 서비스에 대한 완벽한 이해
